### ISSUE TITLE
Bug with chipped skulls

### ISSUE THREAD

**Issue by Neb2566** [CollinHerber/d2r-reimagined-mod#6]
Making chipped skulls into a grabber makes it into a Chipped Sapphire Grabber with chipped skull icon, cannot craft gem bag either.

**Comment by CollinHerber** [comment]
This has been resolved with 1.13.2

**Comment by Neb2566** [comment]
I see, I guess I messed up somwhere trying to craft the bag, tried again now and tripple checked all the gems and it worked. Any easier way to add gems to the bag then to unstack each and every gem and then cube it with the bag?
